### PR TITLE
Catalan language file contribution.

### PR DESCRIPTION
**Pull request by pau-minoves**

### CODE REVIEW

**Comment by fulldecent** [comment]
Looks great

**Comment by alixandru** [comment]
Thanks for contributing!

One comment though: I would rather keep the styling of the buttons separate from the code. There's a provided CSS file ([`qa-open-login.css`](https://github.com/alixandru/q2a-open-login/blob/master/qa-open-login.css)) where you could put the `font-size` definition. Can you update the files so I can merge them in?

Thanks!
Alex

**Comment by pau-minoves** [comment]
I can't recall what that css was for. I've deleted as is out of place in this pull request any way.

All yours!

**Comment by alixandru** [comment]
Perfect! I merged it in. Thanks!

**Pull request merged**
