### PR TITLE
Upgraded HybridAuth from "2.11.0" to "2.15.1", also fixed Google, Live and Twitter

### PR DESCRIPTION
**Pull request by bertrandgorge**
* Upgraded HybridAuth from "2.11.0" to "2.15.1"
* Added a specific endpoint for MS Live and Twitter (note that those endpoints need to be copied to the root of q2a) - Should fix issue #53
* Added function qa_open_login_get_provider_scope in qa-open-utils, that returns the scope for each provider (the default scope for Google, Live, was way too permissive). This function is used in both qa_open-login.php and qa-open-page-logins.php (instead of being duplicated as it used to be for facebook). This fixes https://www.question2answer.org/qa/76682/login-google-login-remove-asking-permission-delete-contacts

Tested and working: 
* MS Live
* Twitter
* Google

Tested but not working:
* Facebook

Next patch I'll try to upgrade HybridAuth to version 3 (version 2 is not maintained anymore and given the pace of changes in each provider's implementation, it's better to be current)

### CODE REVIEW

**Review by alixandru — CHANGES_REQUESTED** [review]
Hi and thanks for taking the time to submit the pull request. If you could just disable the debug mode in qa-open-login and qa-open-page-logins files I could merge the changes right away.
Thank you,
Alex

**Comment by bertrandgorge** [comment]
Sure ! Sorry about that...! You should be able to merge it now.

**Comment by alixandru** [comment]
Reopening so I can merge the changes in

**Comment by bertrandgorge** [comment]
Hello Alixandru, I closed the merge request because for some reason it took a commit that did not belong to it, and I mixed everything up at that point :-)

I've just submitted a new patch that includes HybridAuth v3 - there's a few conflict because I didn't pull your merge before, but you can just keep my changes I believe.

You'll see that beyond the obvious files that have been changed from HybridAuth v2 to V3, there was not too much trouble upgrading, and from the tests that I could run, it works without any issue for at least Google, Facebook and Twitter.

If you have any questions we can talk of https://gitter.im or anything.

**Pull request merged**
